# Generated by Django 6.0.2 on 2026-02-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
            preserve_default=False,
        ),
    ]
